### ISSUE TITLE
Instructions: mention that one can edit the properties of a packet

### ISSUE THREAD

**Issue by guntbert** [errorinn/netsim#3]
Although young people will find this out probably much faster than I did it might be beneficial to tell them how to edit the properties of a packet they generated.

**Comment by errorinn** [comment]
I think the "Level Objectives" section on Basics 2 should account for this (it's pretty wordy already)

**Comment by guntbert** [comment]
I worded this issue badly
- I was not talking about packets "on the fly" - the properties of those you can see as stated in Basics 2
- instead I was talking about the packet template (see red arrow below). It was rather by accident that I discovered the possibility to edit that template

![image](https://cloud.githubusercontent.com/assets/1173238/26556733/9a97ffcc-449c-11e7-9d6b-dd57d05da680.png)
